name: CI - Test, Coverage & SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build, Test & Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
          cache: gradle

      - name: Cache SonarQube packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests, JaCoCo & SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test jacocoTestReport sonar --info

      - name: Generate Allure Report
        if: always()
        run: ./gradlew allureReport

      - name: Upload Kotest HTML report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: kotest-report
          path: build/reports/tests/test/

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html/

      - name: Upload test results XML
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results
          path: build/test-results/test/

      - name: Upload Pages Artifact
        if: always() && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/reports/allure-report

  deploy:
    name: Deploy to GitHub Pages
    if: always() && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5